# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            A BLOG
description:      Marco's NoteBook
url:              https://marcoqin.github.io
disqus.shortname: marcoqin
reading_time: true
words_per_minute: 200

author:
  name:           'Marco Qin'
  url:            https://github.com/MarcoQin

paginate:         7
timezone:    Asia/Shanghai

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
